# MSMT Dataset Configurations
# Use these configurations for different datasets

# PEMS Traffic Datasets
PEMS03:
  data_path: "dataset/PEMS03"
  num_nodes: 358
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 128
  batch_size: 16
  learning_rate: 0.001
  epochs: 300
  early_stopping_patience: 100
  memory_size: 4

PEMS04:
  data_path: "dataset/PEMS04"
  num_nodes: 307
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 128
  batch_size: 16
  learning_rate: 0.001
  epochs: 500
  early_stopping_patience: 100
  memory_size: 4

PEMS07:
  data_path: "dataset/PEMS07"
  num_nodes: 883
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 128
  batch_size: 8  # Larger dataset, smaller batch
  learning_rate: 0.001
  epochs: 300
  early_stopping_patience: 80
  memory_size: 6

PEMS08:
  data_path: "dataset/PEMS08"
  num_nodes: 170
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 128
  batch_size: 16
  learning_rate: 0.001
  epochs: 500
  early_stopping_patience: 100
  memory_size: 4

# Mobility Datasets
bike_drop:
  data_path: "dataset/bike_drop"
  num_nodes: 250
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 96
  batch_size: 16
  learning_rate: 0.001
  epochs: 300
  early_stopping_patience: 80
  memory_size: 4

taxi_drop:
  data_path: "dataset/taxi_drop"
  num_nodes: 266
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 96
  batch_size: 16
  learning_rate: 0.001
  epochs: 300
  early_stopping_patience: 80
  memory_size: 4


# Default Configuration
default:
  data_path: "data/PEMS04"
  num_nodes: 307
  input_len: 12
  output_len: 12
  input_dim: 3
  channels: 128
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.0001
  dropout: 0.1
  epochs: 500
  early_stopping_patience: 100
  memory_size: 4
  print_every: 50
  device: "cuda:0"